language: c
dist: xenial
sudo: false
cache:
  apt: true
  pip: true
env:
    # TRAVIS_PYTHON_VERSION is only needed for neo's setup.py
    # OPENBLAS_NUM_THREADS=1 avoid slowdowns:
    # https://github.com/xianyi/OpenBLAS/issues/731
    global: PYTHON_VERSION=3.6 DISPLAY=:99.0 MNE_LOGGING_LEVEL=warning TEST_LOCATION=src
            PIP_DEPENDENCIES="codecov nitime"
            TRAVIS_PYTHON_VERSION=3.6 CONDA_VERSION=">=4.3.27"
            OPENBLAS_NUM_THREADS=1

matrix:
    include:
        # Linux
        - os: linux
          env: CONDA_ENVIRONMENT="environment.yml"

        # OSX conda
        - os: osx
          env: CONDA_ENVIRONMENT="environment.yml"

# Setup anaconda
before_install:
    - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
      fi;
    - git clone https://github.com/astropy/ci-helpers.git;
    - source ci-helpers/travis/setup_conda.sh;
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
          pip install --upgrade pyqt5>=5.10 pylsl;
      else
          conda install -c tstenner pylsl;
      fi
    # Don't source mne_setup_sh here because changing PATH etc. can't be done in a script
    - if [ "${DEPS}" == "" ]; then
        export MNE_ROOT="${PWD}/minimal_cmds";
        export PATH=${MNE_ROOT}/bin:$PATH;
        if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
          curl https://staff.washington.edu/larsoner/minimal_cmds.tar.gz | tar xz;
          export LD_LIBRARY_PATH=${MNE_ROOT}/lib:$LD_LIBRARY_PATH;
          export NEUROMAG2FT_ROOT="${PWD}/minimal_cmds/bin";
        else
          curl https://staff.washington.edu/larsoner/minimal_cmds_osx.tar.gz | tar xz;
          export DYLD_LIBRARY_PATH=${MNE_ROOT}/lib:$DYLD_LIBRARY_PATH;
        fi;
        mne_surf2bem --version;
      fi;

install:
    # Rvm overrides cd with a function so that it can hook into it to run
    # some scripts, see https://github.com/travis-ci/travis-ci/issues/8703
    - if [ "${TRAVIS_OS_NAME}" == "osx" ]; then
        unset -f cd;
      fi;
    # Suppress the parallel outputs for logging cleanliness
    - python setup.py build
    - python setup.py install
    - python -c "import mne_realtime; mne_realtime.__version__"


script:
    - echo "Print locale "
    - locale
    - echo "Other stuff"
    - pytest -v --cov=mne_realtime --pyargs mne_realtime

after_script:
    - cp .coverage $TRAVIS_BUILD_DIR
    - codecov --root $TRAVIS_BUILD_DIR || echo "codecov upload failed"
